# backend/api/wrangler.toml
name = "broad-darkness-f0a6"
main = "src/index.js"
compatibility_date = "2023-06-28"

# Proměnné prostředí pro JWT
[vars]
JWT_SECRET = "development-secret-change-in-production"

# KV Storage pro data aplikace
kv_namespaces = [
  { binding = "USERS", id = "YOUR_KV_ID_HERE", preview_id = "YOUR_PREVIEW_KV_ID_HERE" }
]

# R2 Storage pro soubory a PDF dokumenty
# Odkomentujte pro použití R2 Storage
# [[r2_buckets]]
# binding = "FILES"
# bucket_name = "offer-system-files"
