# backend/api/wrangler.toml
name = "broad-darkness-f0a6"
main = "src/index.js"
compatibility_date = "2023-06-28"

# Proměnné prostředí pro JWT
[vars]
JWT_SECRET = "development-secret-change-in-production"

# KV Storage pro data aplikace
kv_namespaces = [
  { binding = "USERS", id = "YOUR_KV_ID_HERE", preview_id = "YOUR_PREVIEW_KV_ID_HERE" },
  { binding = "PRODUKTY", id = "c7b8323160a546fda26e38c537ef7be8", preview_id = "c7b8323160a546fda26e38c537ef7be8" }
]
